spring:
  application:
    name: Venus

  profiles:
    active: local

server:
  port: 8091
  address: 0.0.0.0
#   Multipart file upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
#********** Swagger Config ***********
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html
  show-actuator: true